version: '3.8'

services:
  cops-and-robbers-redis:
    image: redis:7
    container_name: cops-and-robbers-redis
    restart: always

  cops-and-robbers-app:
    image: copsnro66ers/cops-and-robbers:latest
    container_name: cops-and-robbers-app
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul

      FIREBASE_KEY_PATH: /app/firebase-key.json

      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: cops-and-robbers-redis
      REDIS_PORT: 6379

      ACCESS_SECRET_KEY: ${ACCESS_SECRET_KEY}
      REFRESH_SECRET_KEY: ${REFRESH_SECRET_KEY}
      ACCESS_EXPIRATION: ${ACCESS_EXPIRATION}
      REFRESH_EXPIRATION: ${REFRESH_EXPIRATION}

    volumes:
      - ./firebase-key.json:/app/firebase-key.json
      - /home/ubuntu/log:/log

    depends_on:
      - cops-and-robbers-redis
    restart: always
