version: '3.8'

services:
  cops-and-robbers-redis:
    image: redis:7
    container_name: cops-and-robbers-redis
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
    networks:
      - cops-network
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    pid: "host"
    restart: always

networks:
  cops-network:
    name: cops-network
    driver: bridge
