version: '3.8'

services:
  cops-and-robbers-db:
    image: postgis/postgis:15-3.3
    container_name: cops-and-robbers-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cops_and_robbers_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./prod-db-data:/var/lib/postgresql/data
    restart: always

  cops-and-robbers-redis:
    image: redis:7
    container_name: cops-and-robbers-redis
    restart: always

  cops-and-robbers-app:
    image: copsnro66ers/cops-and-robbers:latest
    container_name: cops-and-robbers-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

      FIREBASE_KEY_PATH: /app/firebase-key.json

      DB_HOST: jdbc:postgresql://cops-and-robbers-db:5432/cops_and_robbers_db
      DB_USERNAME: postgres
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: cops-and-robbers-redis
      REDIS_PORT: 6379

      ACCESS_SECRET_KEY: ${ACCESS_SECRET_KEY}
      REFRESH_SECRET_KEY: ${REFRESH_SECRET_KEY}
      ACCESS_EXPIRATION: ${ACCESS_EXPIRATION}
      REFRESH_EXPIRATION: ${REFRESH_EXPIRATION}

    volumes:
      - ./firebase-key.json:/app/firebase-key.json

    depends_on:
      - cops-and-robbers-db
      - cops-and-robbers-redis
    restart: always
