spring:
  application:
    name: cops-and-robbers

jwt:
  access:
    secret: ${ACCESS_SECRET_KEY}
    expiration: ${ACCESS_EXPIRATION}
  refresh:
    secret: ${REFRESH_SECRET_KEY}
    expiration: ${REFRESH_EXPIRATION}

springdoc:
  swagger-ui:
    path: /docs/swagger
    display-request-duration: true
    persist-authorization: true
    filter: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
