spring:
  application:
    name: cops-and-robbers

  lifecycle:
    timeout-per-shutdown-phase: 60s

  graphql:
    graphiql:
      enabled: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: false
    validate-on-migrate: true
    encoding: UTF-8

  http:
    client:
      connect-timeout: 2s
      read-timeout: 2s

jwt:
  access:
    secret: ${ACCESS_SECRET_KEY}
    expiration: ${ACCESS_EXPIRATION}
  refresh:
    secret: ${REFRESH_SECRET_KEY}
    expiration: ${REFRESH_EXPIRATION}

springdoc:
  swagger-ui:
    path: /docs/swagger
    display-request-duration: true
    persist-authorization: true
    filter: true

encryption:
  secret-key: ${ENCRYPTION_KEY}

geocoding:
  vworld:
    api-key: ${VWORLD_API_KEY:}
  geoapify:
    api-key: ${GEOAPIFY_API_KEY:}

discord:
  webhook:
    bug: ${DISCORD_WEBHOOK_BUG}
    alert: ${DISCORD_WEBHOOK_ALERT:}

server:
  shutdown: graceful

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: always
