spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  flyway:
    enabled: true
    out-of-order: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      log-format: "\n\t[%(category)] %(executionTime)ms\n\t%(sqlSingleLine)"

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
    p6spy: info

firebase:
  key-path: classpath:firebase-key.json
