name: 👮🏻 CI/CD 파이프라인 🥷

on:
  push:
    branches: [ "main" , "chxghee/feat-19-firebase"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:15-3.3
        env:
          POSTGRES_USER: test_cnr
          POSTGRES_PASSWORD: test5678
          POSTGRES_DB: cops_test_db
        ports:
          - 5433:5432
        options: >-
          --tmpfs /var/lib/postgresql/data
          --health-cmd "pg_isready -U test_cnr -d cops_test_db"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

      redis:
        image: redis:latest
        ports:
          - 6380:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 50

    steps:
      - name: 🔄 소스 코드 가져오기
        uses: actions/checkout@v3

      - name: 📝 테스트용 Firebase 더미 키 생성
        run: |
          mkdir -p src/test/resources
          echo '{"type": "service_account", "project_id": "test"}' > src/test/resources/dummy-firebase-key.json

      - name: ☕ JDK 21 설치
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: 🐘 Gradle 빌드 및 테스트
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: 🐳 Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 📦 Docker 이미지 빌드 및 업로드
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cops-and-robbers:latest

      - name: 🚚 배포 파일 전송 (Compose & Script)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose-prod.yml,scripts/deploy.sh,scripts/logging.sh"
          target: "/home/${{ secrets.EC2_USER }}/cops-and-robbers/"

      - name: 🚀 EC2 배포 및 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          envs: DB_PASSWORD,ACCESS_SECRET_KEY,REFRESH_SECRET_KEY,ACCESS_EXPIRATION,REFRESH_EXPIRATION
          script: |
            chmod +x /home/${{ secrets.EC2_USER }}/cops-and-robbers/scripts/deploy.sh

            /home/${{ secrets.EC2_USER }}/cops-and-robbers/scripts/deploy.sh
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ACCESS_SECRET_KEY: ${{ secrets.ACCESS_SECRET_KEY }}
          REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY }}
          ACCESS_EXPIRATION: ${{ secrets.ACCESS_EXPIRATION }}
          REFRESH_EXPIRATION: ${{ secrets.REFRESH_EXPIRATION }}
